// VAELEN - VaelenSim
// GENERATED by Tools/gen_event_names.py. Do not edit by hand.
//
// The event-type name table: every name this tree declares through
// MakeEventType, beside the FNV-1a hash an Event actually carries.
//
// WHY IT IS NEEDED. An Event stores Hash64 TypeHash and nothing else about
// its identity (Event.h). The name lives at the declaration site, in the
// EventType<T> constant, and never travels with the event - so once an event
// is in a log, an image or a container, the word is gone. Before 17.02 nothing
// in this tree could turn one back.
//
// WHY IT IS GENERATED. A compile-time table would need every module's headers
// in one translation unit, and VaelenSim may not know VaelenMilitary exists.
// This header knows hashes and string literals and depends on nothing.
// Kernel.EventTypes re-runs the generator and diffs, so a new, renamed or
// deleted type fails the build rather than quietly degrading a tool.
//
// WHERE EACH NAME IS DECLARED is one grep away and is deliberately not
// carried here: `grep -rn '"OreLifted"' Source/`. A trailing // path:line on
// every row makes clang-format align a hundred and fifteen comments into a
// column whose position depends on the longest line in the block, so adding one
// long event name reformats the whole table and the diff stops being readable.
//
// STATUS: VALIDATED (Phase 17 task 17.02) - Tests/Run/Test_EventTypes.cpp
#pragma once

#include "Vaelen/Core/CoreTypes.h"
#include "Vaelen/Core/Hash.h"

#include <cstdio>

namespace Vaelen
{
	struct EventTypeName
	{
		Hash64 TypeHash;
		const char* Name;
	};

	/// Sorted by hash, so a lookup is a binary search and no allocation.
	inline constexpr EventTypeName EventTypeNames[] = {
		{0x08483841bdf5f80bull, "PersonMoved"},
		{0x08b108174d079583ull, "ReligionFounded"},
		{0x0c0c78eb9c177c5cull, "MapWritten"},
		{0x0e0a8cc1372c59c6ull, "ArmyDisbanded"},
		{0x0e66b92913b9059eull, "DecisionMade"},
		{0x0fb64b229d6053c0ull, "FactionFormed"},
		{0x0fd0c34eff719de0ull, "DuesPaid"},
		{0x114546d69d6eab95ull, "EraClosed"},
		{0x12642cf2680a9e50ull, "FactionRevolted"},
		{0x1350dc61e2922e22ull, "Condemned"},
		{0x1403cb05dae9fb66ull, "WarBegan"},
		{0x14694a184851caf6ull, "ArmyMarched"},
		{0x173b00b7dabe8fe9ull, "RoadCut"},
		{0x190e051bff7c267full, "RouteOpened"},
		{0x1b63ab2cc8b04aa7ull, "OrganizationFounded"},
		{0x1c095067a1db6b5aull, "MigrationWave"},
		{0x1cbe569c79a07e27ull, "SuccessionSettled"},
		{0x1dead669acef32b4ull, "LanguageFounded"},
		{0x1f18ab1ee69ac810ull, "ArmyRaised"},
		{0x21192f77ef3ecfcfull, "ArmyStarved"},
		{0x219c258c80929a48ull, "PlayerRefused"},
		{0x2202c523c9e3764aull, "RouteClosed"},
		{0x25ea26ab779b081cull, "OrganizationDisbanded"},
		{0x2a3ed812db897e40ull, "FamilyExtinct"},
		{0x2b60a8739fc5f0deull, "ContactMade"},
		{0x2d290307624f2addull, "PlayerActed"},
		{0x2ee673cfc6d116d1ull, "WinterForeseen"},
		{0x33b1a03f098bb9fcull, "BuildingFell"},
		{0x349a180144c611c6ull, "RegionClaimed"},
		{0x39874887a6682902ull, "FamilyFounded"},
		{0x3b6234eb160360d7ull, "RegionPinned"},
		{0x3c0fb8f2ae73228aull, "FortuneChanged"},
		{0x3d2dc5a7a2f26d01ull, "SeamWorkedOut"},
		{0x3ef5d37d60fbb6d1ull, "ArmyBroken"},
		{0x4200f34b136055d4ull, "Pardoned"},
		{0x4288c8135de7434bull, "HeadSeated"},
		{0x446dae94010ad85eull, "SuccessionDisputed"},
		{0x4786a62eb4c3ca85ull, "GoodsCarried"},
		{0x47bad729113f01abull, "BondEntered"},
		{0x489f1da4f5c154e3ull, "NameTravelled"},
		{0x49ac3bd87a7ffbf8ull, "LevyReleased"},
		{0x4abf43c07a4456feull, "Omen"},
		{0x4c9d1b8be443a7eaull, "ArmyForaged"},
		{0x503a4e9cc8951520ull, "DocumentCopied"},
		{0x52f91a87e7f745e8ull, "BattleFought"},
		{0x53358c6ff642820full, "PersonBorn"},
		{0x54f55f05dd672cf1ull, "StockInherited"},
		{0x586ed67b7f5e6ec9ull, "PersonArrived"},
		{0x587b6c53726fa166ull, "RegionContested"},
		{0x5c1d1d23a04fc453ull, "BuildingEnlarged"},
		{0x5c792b9386ae7eb1ull, "LawChanged"},
		{0x5ca753e665b1472dull, "PeopleFled"},
		{0x5fb7ecc33781bde1ull, "PersonLeft"},
		{0x6010a001a6c81d8dull, "ArmyArrived"},
		{0x66aac681ab67b41eull, "PersonDied"},
		{0x67cf39fe4bdeff9full, "OreLifted"},
		{0x69d2ac7936b62d92ull, "RegionSettled"},
		{0x6a3a7665477b2173ull, "RegionLost"},
		{0x6c0ffd666198d766ull, "Named"},
		{0x6e3a62f2ce7a61d0ull, "EraOpened"},
		{0x709b666a0db6b3daull, "MemberLeft"},
		{0x712609c37dc8bec9ull, "StockEndowed"},
		{0x71b632538881a34aull, "DisasterStruck"},
		{0x71ef9fd1d83886bbull, "StanceChanged"},
		{0x73c9f4f49689aa91ull, "MapRead"},
		{0x766bde19322fc75dull, "NormChanged"},
		{0x78bbaed697298402ull, "MemberJoined"},
		{0x7985818e9125d1beull, "HeirNamed"},
		{0x7b08133758d4a00eull, "PriceChanged"},
		{0x7ee1971362a9a854ull, "Schism"},
		{0x8041cc7ed96d3724ull, "PersonMarried"},
		{0x82330c6fff4664fbull, "RulerSeated"},
		{0x84be4a4ae18c9f0dull, "BondLeft"},
		{0x8fc36a4a65fd2c0bull, "DuesUnpaid"},
		{0x8fe6bf3c7de3a2a2ull, "DocumentLost"},
		{0x927b249eb11936d6ull, "HeardOf"},
		{0x942ad945cdbcbbabull, "StockFolded"},
		{0x9755634958f48dc3ull, "DocumentWritten"},
		{0x97b465e01259311full, "SeatTaken"},
		{0x98ca757a150f7670ull, "Shortfall"},
		{0x98edd9b5ce1e05e2ull, "SeatFellVacant"},
		{0xa18ff531a66647beull, "SiegeLaid"},
		{0xa7056fb4ef2ce954ull, "NameForgotten"},
		{0xa7bef26bf43750d1ull, "RaidPlanned"},
		{0xa84927cf72a52d6eull, "StockReturned"},
		{0xa9d609a9ea19fb81ull, "RegionConverted"},
		{0xaa56846740f419a7ull, "WarDead"},
		{0xae6104a7c557e188ull, "DocumentRead"},
		{0xaf97ca73438d3a35ull, "PlaceSettled"},
		{0xb0b7671682ca0df1ull, "PolityDissolved"},
		{0xb6cc6980901b711cull, "UpkeepUnpaid"},
		{0xb7b3635d986a22e9ull, "RoadLost"},
		{0xb868f5b1385536a0ull, "RegionSlipped"},
		{0xbcc8a2f07df3b55aull, "CultureFounded"},
		{0xbf446db77c62b830ull, "SiegeLifted"},
		{0xc013bc96d7941338ull, "ColonyFounded"},
		{0xc27af5866fd8b5e7ull, "SettlementFounded"},
		{0xd35032a7b73b36acull, "Winter"},
		{0xd6fc019482fdc77full, "RegionAbandoned"},
		{0xdb97e7396193d769ull, "PlaceGrew"},
		{0xdc84b039d9e04433ull, "FactionFaded"},
		{0xdf837a605b304a8cull, "RegionAnnexed"},
		{0xe1239d8b5bcdab13ull, "StockSplit"},
		{0xe1ca33971b8f0bd5ull, "RegionPromoted"},
		{0xe5d66ba46ed75f4aull, "SettlementAbandoned"},
		{0xe74ae07ceac8382full, "RegionDemoted"},
		{0xe9c3212c4e244bf0ull, "RegionTaken"},
		{0xe9f40615eb2024b5ull, "StockAdded"},
		{0xeba797a1374574ffull, "LanguageDrifted"},
		{0xeca541053c7fc726ull, "ArmyRetreated"},
		{0xedadc77b908de124ull, "PlaceEmptied"},
		{0xf10e1532cb254d58ull, "StockTaken"},
		{0xf5ca999fac89f035ull, "BuildingRaised"},
		{0xf674f25611676bd2ull, "Harvest"},
		{0xf87e3fe8ad4a9975ull, "PolityFounded"},
		{0xf95ec2b988f82697ull, "CultureSplit"},
		{0xfc2058b7bdf1b75bull, "WarEnded"},
	};

	inline constexpr usize EventTypeNameCount = sizeof(EventTypeNames) / sizeof(EventTypeNames[0]);

	/// The declared name of a type hash.
	///
	/// AN UNKNOWN HASH IS NOT AN ERROR AND NOT AN EMPTY STRING. A log written
	/// by a build with a type this one does not have is a thing that will
	/// happen, and the honest answer is the hash itself - `?0123456789abcdef`,
	/// which a person can grep for. An empty name would make a census print a
	/// blank row and look like a bug in the census.
	///
	/// The buffer is the CALLER's, and per-thread reuse is the caller's problem
	/// to have rather than a static this header hides. 18 bytes: '?', 16 hex
	/// digits, NUL.
	inline const char* NameOfEventType(Hash64 TypeHash, char (&Unknown)[18]) noexcept
	{
		usize Low = 0;
		usize High = EventTypeNameCount;
		while (Low < High)
		{
			const usize Mid = Low + (High - Low) / 2;
			if (EventTypeNames[Mid].TypeHash == TypeHash)
			{
				return EventTypeNames[Mid].Name;
			}
			if (EventTypeNames[Mid].TypeHash < TypeHash)
			{
				Low = Mid + 1;
			}
			else
			{
				High = Mid;
			}
		}
		std::snprintf(Unknown, sizeof(Unknown), "?%016llx", static_cast<unsigned long long>(TypeHash));
		return Unknown;
	}
} // namespace Vaelen
