[/Script/Engine.InputSettings]
; Enhanced Input mappings are introduced in Phase 10 - PLAYER.
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent
