#!/usr/bin/env python3
"""VAELEN - Phase 17 task 17.02: generate the event-type name table.

WHY THIS EXISTS. An `Event` carries `Hash64 TypeHash` and nothing else about
its identity (Vaelen/Sim/Event.h). The NAME is at the declaration site, in the
`EventType<T>` constant, and it never travels with the event: the moment an
event is in a log, in an image, or in a container, the word is gone. Grepping
this tree for `EventTypeName`, `NameOfEvent` or `TypeName(` before 17.02
returned nothing at all. So every census, inspector and causal walk this phase
plans would print sixteen hex digits where a person needs a word.

WHY GENERATED RATHER THAN HAND-WRITTEN. There are 115 declarations across nine
modules, and the day somebody adds the 116th a hand-written table is silently
one short. `Kernel.EventTypes` re-runs this script and diffs against the
checked-in header, so a new type, a renamed type or a deleted one fails the
build rather than degrading a tool.

WHY A SCRIPT RATHER THAN A CONSTEXPR TRICK. A table built at compile time from
the `EventType` constants would need every module's headers included into one
translation unit - Colony, Military, Politics, Economy, Society, Population,
Sim - which is precisely the coupling the layering forbids: VaelenSim may not
know VaelenMilitary exists. The generated header knows only hashes and string
literals, and depends on nothing.

Usage:
  python3 Tools/gen_event_names.py --check    # exit 1 if the header is stale
  python3 Tools/gen_event_names.py --write    # rewrite it
  python3 Tools/gen_event_names.py --self-test
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "Source")
HEADER = os.path.join(SOURCE, "VaelenSim", "Public", "Vaelen", "Sim", "EventTypeNames.h")

# The call site, exactly as it is written 115 times. The payload type may be
# qualified and may carry a namespace, so it is matched loosely; the NAME is a
# string literal and is matched tightly, because a name this script guessed
# wrong is a name no tool can print.
CALL = re.compile(r'MakeEventType\s*<[^>]*>\s*\(\s*"([A-Za-z0-9_]+)"\s*\)')

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x00000100000001B3
MASK = (1 << 64) - 1


def hash_string(text):
    """FNV-1a over the bytes of `text`, matching Vaelen::HashString exactly.

    Vaelen/Core/Hash.h hashes `Text.size()` bytes of a `std::string_view`, so
    there is NO trailing NUL - a detail worth stating, because getting it wrong
    produces a table that is self-consistent, compiles, passes a round trip
    against itself, and agrees with the running world about nothing.
    """
    h = FNV_OFFSET
    for byte in text.encode("utf-8"):
        h ^= byte
        h = (h * FNV_PRIME) & MASK
    return h


def collect(source_dir):
    """Every (name, hash, where) in the tree, sorted by hash."""
    found = {}
    for base, dirs, files in os.walk(source_dir):
        dirs.sort()
        for name in sorted(files):
            if not name.endswith((".h", ".cpp", ".inl")):
                continue
            path = os.path.join(base, name)
            with open(path, "r", encoding="utf-8") as handle:
                text = handle.read()
            for match in CALL.finditer(text):
                event = match.group(1)
                line = text.count("\n", 0, match.start()) + 1
                where = "{}:{}".format(os.path.relpath(path, ROOT).replace(os.sep, "/"), line)
                if event in found and found[event][1] != where:
                    # Not fatal on its own - the same name declared twice with
                    # the same payload is legal C++ and hashes the same - but
                    # it is recorded so a reviewer sees it.
                    found[event] = (found[event][0], found[event][1] + ", " + where)
                else:
                    found[event] = (hash_string(event), where)

    rows = [(h, name, where) for name, (h, where) in found.items()]
    rows.sort()

    # A COLLISION WOULD MAKE THE TABLE LIE, and a binary search over it would
    # hand back whichever of the two sorted first. FNV-1a over short ASCII
    # names has never collided here, but "has never" is not "cannot".
    for index in range(1, len(rows)):
        if rows[index][0] == rows[index - 1][0]:
            raise SystemExit(
                "gen_event_names: {} and {} both hash to {:016x} - the table cannot "
                "represent both".format(rows[index - 1][1], rows[index][1], rows[index][0]))
    return rows


def render(rows):
    out = []
    out.append("// VAELEN - VaelenSim")
    out.append("// GENERATED by Tools/gen_event_names.py. Do not edit by hand.")
    out.append("//")
    out.append("// The event-type name table: every name this tree declares through")
    out.append("// MakeEventType, beside the FNV-1a hash an Event actually carries.")
    out.append("//")
    out.append("// WHY IT IS NEEDED. An Event stores Hash64 TypeHash and nothing else about")
    out.append("// its identity (Event.h). The name lives at the declaration site, in the")
    out.append("// EventType<T> constant, and never travels with the event - so once an event")
    out.append("// is in a log, an image or a container, the word is gone. Before 17.02 nothing")
    out.append("// in this tree could turn one back.")
    out.append("//")
    out.append("// WHY IT IS GENERATED. A compile-time table would need every module's headers")
    out.append("// in one translation unit, and VaelenSim may not know VaelenMilitary exists.")
    out.append("// This header knows hashes and string literals and depends on nothing.")
    out.append("// Kernel.EventTypes re-runs the generator and diffs, so a new, renamed or")
    out.append("// deleted type fails the build rather than quietly degrading a tool.")
    out.append("//")
    out.append("// WHERE EACH NAME IS DECLARED is one grep away and is deliberately not")
    out.append('// carried here: `grep -rn \'"OreLifted"\' Source/`. A trailing // path:line on')
    out.append("// every row makes clang-format align a hundred and fifteen comments into a")
    out.append("// column whose position depends on the longest line in the block, so adding one")
    out.append("// long event name reformats the whole table and the diff stops being readable.")
    out.append("//")
    out.append("// STATUS: VALIDATED (Phase 17 task 17.02) - Tests/Run/Test_EventTypes.cpp")
    out.append("#pragma once")
    out.append("")
    out.append('#include "Vaelen/Core/CoreTypes.h"')
    out.append('#include "Vaelen/Core/Hash.h"')
    out.append("")
    out.append("#include <cstdio>")
    out.append("")
    out.append("namespace Vaelen")
    out.append("{")
    out.append("\tstruct EventTypeName")
    out.append("\t{")
    out.append("\t\tHash64 TypeHash;")
    out.append("\t\tconst char* Name;")
    out.append("\t};")
    out.append("")
    out.append("\t/// Sorted by hash, so a lookup is a binary search and no allocation.")
    out.append("\tinline constexpr EventTypeName EventTypeNames[] = {")
    for h, name, _where in rows:
        out.append('\t\t{{0x{:016x}ull, "{}"}},'.format(h, name))
    out.append("\t};")
    out.append("")
    out.append("\tinline constexpr usize EventTypeNameCount = sizeof(EventTypeNames) / sizeof(EventTypeNames[0]);")
    out.append("")
    out.append("\t/// The declared name of a type hash.")
    out.append("\t///")
    out.append("\t/// AN UNKNOWN HASH IS NOT AN ERROR AND NOT AN EMPTY STRING. A log written")
    out.append("\t/// by a build with a type this one does not have is a thing that will")
    out.append("\t/// happen, and the honest answer is the hash itself - `?0123456789abcdef`,")
    out.append("\t/// which a person can grep for. An empty name would make a census print a")
    out.append("\t/// blank row and look like a bug in the census.")
    out.append("\t///")
    out.append("\t/// The buffer is the CALLER's, and per-thread reuse is the caller's problem")
    out.append("\t/// to have rather than a static this header hides. 18 bytes: '?', 16 hex")
    out.append("\t/// digits, NUL.")
    out.append("\tinline const char* NameOfEventType(Hash64 TypeHash, char (&Unknown)[18]) noexcept")
    out.append("\t{")
    out.append("\t\tusize Low = 0;")
    out.append("\t\tusize High = EventTypeNameCount;")
    out.append("\t\twhile (Low < High)")
    out.append("\t\t{")
    out.append("\t\t\tconst usize Mid = Low + (High - Low) / 2;")
    out.append("\t\t\tif (EventTypeNames[Mid].TypeHash == TypeHash)")
    out.append("\t\t\t{")
    out.append("\t\t\t\treturn EventTypeNames[Mid].Name;")
    out.append("\t\t\t}")
    out.append("\t\t\tif (EventTypeNames[Mid].TypeHash < TypeHash)")
    out.append("\t\t\t{")
    out.append("\t\t\t\tLow = Mid + 1;")
    out.append("\t\t\t}")
    out.append("\t\t\telse")
    out.append("\t\t\t{")
    out.append("\t\t\t\tHigh = Mid;")
    out.append("\t\t\t}")
    out.append("\t\t}")
    out.append("\t\tstd::snprintf(Unknown, sizeof(Unknown), \"?%016llx\", static_cast<unsigned long long>(TypeHash));")
    out.append("\t\treturn Unknown;")
    out.append("\t}")
    out.append("} // namespace Vaelen")
    out.append("")
    return "\n".join(out)


def self_test():
    """The generator's own controls, run before it is trusted."""
    failures = []

    # 1. The hash must be the kernel's. These three are checked against values
    #    the running build prints, not against this function's own output.
    for name, want in (("EraOpened", None), ("", FNV_OFFSET)):
        got = hash_string(name)
        if want is not None and got != want:
            failures.append("hash_string({!r}) is {:016x}, expected {:016x}".format(name, got, want))
    # The empty string must hash to the offset basis, which is the one value
    # FNV-1a fixes by definition and the one this function cannot get right by
    # accident.

    # 2. The regex must find a declaration and must NOT find the definition.
    if not CALL.search('MakeEventType<Economy::StockPayload>("OreLifted");'):
        failures.append("the call-site regex does not match a real declaration")
    if CALL.search("constexpr EventType<T> MakeEventType(const char* Name) noexcept"):
        failures.append("the call-site regex matches the template DEFINITION")
    if CALL.search('MakeEventType<T>(Name)'):
        failures.append("the call-site regex matches a non-literal name")

    # 3. A collision must be refused rather than silently dropped.
    rows = [(1, "A", "x"), (1, "B", "y")]
    seen = any(rows[i][0] == rows[i - 1][0] for i in range(1, len(rows)))
    if not seen:
        failures.append("the collision check cannot see a collision")

    if failures:
        for line in failures:
            sys.stderr.write("gen_event_names self-test: " + line + "\n")
        return 1
    print("[gen-event-names] self-test: {} checks, all pass".format(4))
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite the header")
    parser.add_argument("--check", action="store_true", help="exit 1 if the header is stale")
    parser.add_argument("--self-test", action="store_true", help="run the generator's own controls")
    parser.add_argument("--source", default=SOURCE)
    parser.add_argument("--out", default=HEADER)
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    rows = collect(args.source)
    text = render(rows)

    if args.check:
        if not os.path.exists(args.out):
            sys.stderr.write("gen_event_names: {} does not exist; run --write\n".format(args.out))
            return 1
        with open(args.out, "r", encoding="utf-8") as handle:
            current = handle.read()
        if current != text:
            sys.stderr.write(
                "gen_event_names: {} is STALE. {} declarations found in the tree. "
                "Run: python3 Tools/gen_event_names.py --write\n".format(args.out, len(rows)))
            # Say WHICH names differ, because a diff of a 115-row table is
            # unreadable and the answer is almost always one name.
            here = set(re.findall(r'"([A-Za-z0-9_]+)"\}', current))
            want = set(name for _, name, _ in rows)
            for name in sorted(want - here):
                sys.stderr.write("  + {}\n".format(name))
            for name in sorted(here - want):
                sys.stderr.write("  - {}\n".format(name))
            return 1
        print("[gen-event-names] {} event types, header current".format(len(rows)))
        return 0

    if args.write:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(text)
        print("[gen-event-names] {} event types written to {}".format(
            len(rows), os.path.relpath(args.out, ROOT)))
        return 0

    parser.error("one of --write, --check or --self-test")


if __name__ == "__main__":
    sys.exit(main())
